spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/servicedesk
    username: servicedesk
    password: servicedesk
  mail:
    host: localhost
    port: 1025

app:
  jwt:
    secret: wWsi5qz+kWDbJuNrFyzpgu4YyGDrb/k1mebFmC+5mWg=
  storage:
    bucket: servicedesk-attachments
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    region: us-east-1
